version: '3.8'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - 'DJANGO_SECRET_KEY=4c-f-+jym0l*t(3qipm(a+28it16ast3_3nwpv8n0@!$$^m+pb_'
      - 'DJANGO_DEBUG=True'
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: